// Generated by https://quicktype.io

export interface noticiasDBNow {
    status:       string;
    totalResults: number;
    articles:     Noticias[];
}

export interface Noticias {
    source:      Source;
    author:      null | string;
    title:       string;
    description: null | string;
    url:         string;
    urlToImage:  null | string;
    publishedAt: string;
    content:     null | string;
}

export interface Source {
    id:   null | string;
    name: string;
}
